
CLASSES = [2,3,10,14,18]
NUM_CLASSES = 5
NUM_REPS = 5
REP_TIME = 5
REST_TIME = 1

WINDOW_SIZE = 200
WINDOW_INCREMENT = 10
EPOCH = 10
SAMPLING = 1010
MAJORITY_VOTE=7
SAMPLING=1010
FILTER = False
VIRTUAL = False
PORT = None

BASE_PATH = "C:/GIT/Datasets/Libemg/"
SESSION = "TestLib"
MODEL_NAME = "libemg_torch_cnn_TestVideo_829_24-10-28_21h37.pth"
MEDIA_PATH = "./media-test/"
MODEL_PATH = f"{BASE_PATH}{SESSION}/{MODEL_NAME}"
DATAFOLDER = f"{BASE_PATH}{SESSION}/"
DATASETS_PATH = f"{BASE_PATH}{SESSION}/"
SAVE_PATH = f"{BASE_PATH}{SESSION}/"